language: python
services:
  - mongodb
python:
  - "2.7"
install:
  - pip install -r requirements.txt 
  - pip install coveralls
# command to run tests
env:
  - DJANGO_VERSION=1.5
script:
  - ./start_local_popit_api.bash
  - coverage run --source=elections manage.py test elections
  - coverage report -m
after_script:
  - coveralls --verbose